// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbdmxgkkjekiaqpsyeib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZG14Z2tramVraWFxcHN5ZWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjYwNDMsImV4cCI6MjA2NTg0MjA0M30.5vjMSrOBuwGtapaAcZDLk3QJfJRTGIY374xXpAUYfI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);